MVC_Auth_Facebook/MVC_Auth_Facebook/Controllers/FlickController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Auth_Facebook.Controllers
{

    public class FlickController : Controller
    {
        //
        // GET: /Flick/

        public ActionResult Index()
        {
            return PartialView("_flickrphotospartial");
        }

    }
}

MVC_Auth_Facebook/MVC_Auth_Facebook/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Auth_Facebook.Controllers
{
    public class VideoController : Controller
    {
        //
        // GET: /Video/

        public ActionResult Index()
        {
            return PartialView("_FeaturedVideoPartial");
        }

        public ActionResult ViewChanel(string ChanelName)
        {
            ViewBag.ChanelName = ChanelName;
            return View();
        }
    }
}

MVC_Auth_Facebook/MVC_Auth_Facebook/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace MVC_Auth_Facebook.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl)
        {
            returnUrl = "/Customers/";
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_FeaturedVideoPartial.cshtml
<h2>Top 10 Video các kênh video trên youtube đang được quan tâm</h2>
                    <div class="video"> <img src="/../Images/_video.jpg" alt="" /> </div>
                    <!-- end featured video -->
                    <!-- begin tags -->
             
                    <div class="tags"> </div>
                    <!-- end tags -->
                    <!-- BEGIN left -->
                    <div class="l sbar">
                        <!-- begin categories -->
                       
                        <ul>
                            <li><a href="/Video/ViewChanel?ChanelName=bongdawap">Bóng đá</a></li>                            
                            <li><a href="/Video/ViewChanel?ChanelName=game8vn">Game8vn</a></li>
                            <li><a href="/Video/ViewChanel?ChanelName=kipkay">KipKay</a></li>
                            <li><a href="/Video/ViewChanel?ChanelName=freddiew">RocketJump</a></li>
                       
                        </ul>
                       
                    </div>
                    <!-- END left -->
                    <!-- BEGIN right -->
                     <div class="r sbar">
                        <!-- begin categories -->
                       
                        <ul>                            
                            <li><a href="/Video/ViewChanel?ChanelName=fashiontv">FashionTV</a></li>
                            <li><a href="/Video/ViewChanel?ChanelName=VICTORIASSECRET">Victoria Secret</a></li>
                            <li><a href="/Video/ViewChanel?ChanelName=HouseholdHacker">HouseholdHacker</a></li>
                            <li><a href="/Video/ViewChanel?ChanelName=advicesmedia">Advices Media</a></li>
                        
                        </ul>
                       
                    </div>
                    <!-- END right -->

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_HeaderPartial.Mobile 1.cshtml
<script src="~/Scripts/knockout-2.1.0.js"></script>
<script src="~/Scripts/knockoutFeeds.js"></script>

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_HeaderPartial.cshtml
<div id="header">
    <ul>
        <li class="#"><a href="#">Trang chủ</a></li>
        <li><a href="#">Thông Tin</a></li>
        
        <li><a href="#">Liên kết trang</a></li>
    </ul>
    @Html.Partial("_ViewSwitcher")
    @if (Request.IsAuthenticated)
    {
            <p class="links"><a href="/Account/Manage">Xin chào! @User.Identity.Name</a> |<a href="/Account/LogOff">Đăng xuất</a></p>
    }
    else
    {
            <p class="links"><a href="/Account/Login">Đăng nhập</a> | <a href="/Account/Register">Đăng kí </a>  | <a href="/Account/Login">Facebook</a> </p>

    }
    <div class="break"></div>
    <div class="logo">
        <h1><a href="#">The Web News</a></h1>
        <p></p>
    </div>
    @*<div class="ad468x60"> <a href="#"><img src="/../Images/ad468x60.gif" alt="" /></a> </div>*@
    <div class="break"></div>
    <ol data-bind="foreach:  Feeds">
        <li>
            <a data-bind="attr: { href: '/Customers/Index?FeedID='+FeedID}, text : UrlFeed "></a>            
        </li>           
    </ol>
    <div class="break"></div>
</div>

<script src="~/Scripts/knockout-2.1.0.js"></script>
<script src="~/Scripts/knockoutFeeds.js"></script>
<script type="text/javascript">    </script>

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>
        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>The Web News</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="~/Content/style.css" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Styles.Render("~/Content/themes/base/css")
    @RenderSection("scripts", required: false)
    <link type="text/css" href="~/Content/lightbox2/css/lightbox.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Content/lightbox2/js/lightbox-2.6.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
</head>
<body>
    <!-- BEGIN wrapper -->
    <div id="wrapper">
        <!-- BEGIN header -->
        @Html.Partial("_HeaderPartial")

        <!-- END header -->
        <!-- BEGIN content -->
        <div id="content">
            <!-- begin post -->
            @RenderBody()
            <!-- end post navigation -->
        </div>
        <!-- END content -->
        <!-- BEGIN sidebar -->
        <div id="sidebar">
            <!-- begin ads -->
            <div class="ads">
                <a href="#">
                    <img src="/../Images/babycute.jpg" alt="" /></a> <a href="#">
                        <img src="/../Images/Cute.jpg" alt="" /></a> <a href="#">
                            <img src="/../Images/Cute-Little.jpg" alt="" /></a> <a href="#">
                                <img src="/../Images/Smooches.jpg" alt="" /></a>
            </div>
            <!-- end ads -->
            <div class="wrapper">
                <!-- begin popular posts -->
                <div id="PopularPosts">
                    <h2>Danh Mục Tin Tức</h2>
                    <ul data-bind="foreach:  Feeds">
                        <li><a data-bind="attr: { href: '/Customers/Index?FeedID='+FeedID}, text : UrlChildFeed "></a></li>
                    </ul>
                </div>
            </div>
            <!-- begin search -->
            <form class="search" action="#">
                <input type="text" name="s" id="Search" style="height: 20px;" />
                <button type="submit">Search</button>
            </form>
            <!-- end search -->
            <div class="wrapper">
                <!-- begin popular posts -->
                <div id="PopularPosts">

                    <h2>Thông Tin HOT</h2>
                    <ul>
                        @if (Request.IsAuthenticated)
                        {
                            <li>Bạn đang đọc báo trên trang <b>@ViewBag.UrlFeed</b> <br />
                                Mục:<b style="color:red">@ViewBag.UrlChildFeed</b><br />
                                Nếu bạn quan tâm đến tin tức trong mục này.Bạn hãy click vào link bên dưới. Chúng tôi sẽ
                                    sẽ gửi tới mail của bạn khi hệ thống cập nhật tin mới :) 
                                
                            </li>
                            <a href="http://thenews.apphb.com/Customers/RegisterFavorite?LinkFavorite=@ViewBag.LinkFavorite"><b>Đăng ký favorite </b></a>
                        }

                        else
                        {
                            <li>
                                <p style="color:red">Đăng ký tài khoản ngay để có thể sử dụng chức năng Favorite.<br />
                                     Chúng tôi sẽ gửi thông báo đến bạn ngay khi có những tin tức mới nhất.</p>
                            </li>
                        }

                    </ul>


                </div>

                <!-- end popular posts -->
                <!-- begin flickr photos -->
                @Html.Action("Index", "Flick")
                @*                    @Html.Partial("_flickrphotospartial")*@
                <!-- end flickr photos -->
                <!-- begin featured video -->
                @Html.Action("Index", "Video")
                @*                    @Html.Partial("_FeaturedVideoPartial")*@

            </div>
        </div>
        <!-- END sidebar -->
        <!-- BEGIN footer -->
        <div id="footer">
            <p>Copyright &copy; 2014 - <a>The Web News</a> &middot; All Rights Reserved</p>
            <p>Template by: <a>Phạm Tuyên Designer</a> | Get More <a>Đại Học Khoa Học Tự Nhiên</a></p>
        </div>
        <!-- END footer -->
    </div>
    <!-- END wrapper -->
    @*<div align=center>This template  downloaded form <a href='#'>free website templates</a></div>*@
</body>
</html>
<script src="~/Scripts/knockout-2.1.0.js"></script>
<script type="text/javascript">
    var EmpViewModel = function () {
        //Make the self as 'this' reference
        var self = this;
        //Declare observable which will be bind with UI
        self.FeedID = ko.observable("");
        self.UrlFeed = ko.observable("");
        self.UrlChildFeed = ko.observable("");
        self.UrlSubFeed = ko.observable("");
        self.xpathUrlPagingFeed = ko.observable("");
        self.XpathUrlFeed = ko.observable("");
        self.XpathTilte = ko.observable("");
        self.XpathPublishedDate = ko.observable("");
        self.XpathSummary = ko.observable("");
        self.XpathImageUrl = ko.observable("");
        self.XpathUrlSub = ko.observable("");
        self.Flag = ko.observable("");

        //The Object which stored data entered in the observables
        var EmpData = {
            FeedID: self.FeedID,
            UrlFeed: self.UrlFeed,
            UrlChildFeed: self.UrlChildFeed,
            UrlSubFeed: self.UrlSubFeed,
            xpathUrlPagingFeed: self.xpathUrlPagingFeed,
            XpathUrlFeed: self.XpathUrlFeed,
            XpathTilte: self.XpathTilte,
            XpathPublishedDate: self.XpathPublishedDate,
            XpathSummary: self.XpathSummary,
            XpathImageUrl: self.XpathImageUrl,
            XpathUrlSub: self.XpathUrlSub,
            Flag: self.Flag
        };

        //Declare an ObservableArray for Storing the JSON Response
        self.Feeds = ko.observableArray([]);
        GetFeeds(); //Call the Function which gets all records using ajax call      
        function GetFeeds() {
            //Ajax Call Get All Employee Records
            $.ajax({
                type: "GET",
                url: "http://cktapp.apphb.com/api/Feeds?UrlFeed=@ViewBag.UrlFeed",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    self.Feeds(data); //Put the response in ObservableArray
                },
                error: function (error) {
                    // alert(error.status + "<--and--> " + error.statusText);
                }
            });
            //Ends Here
        }
    };
    ko.applyBindings(new EmpViewModel());
</script>

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_Layout.cshtml.LOCAL.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>The Web News</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="~/Content/style.css" />
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/jqueryui")
            @Scripts.Render("~/bundles/jqueryval")
            @Styles.Render("~/Content/themes/base/css")
            @RenderSection("scripts",required:false)
        <link type="text/css" href="~/Content/lightbox2/css/lightbox.css" rel="stylesheet" />
        <script type="text/javascript" src="~/Content/lightbox2/js/lightbox-2.6.min.js"></script>
        <script src="~/Content/js/bootstrap.min.js"></script>
        <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
        <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    </head>
    <body>
        <!-- BEGIN wrapper -->
        <div id="wrapper">
            <!-- BEGIN header -->
            @Html.Partial("_HeaderPartial")







            <!-- END header -->
            <!-- BEGIN content -->
            <div id="content">
                <!-- begin post -->
                @RenderBody()
                <!-- end post navigation -->
            </div>
            <!-- END content -->
            <!-- BEGIN sidebar -->
            <div id="sidebar">
                <!-- begin ads -->
                <div class="ads"> <a href="#"><img src="/../Images/babycute.jpg" alt="" /></a> <a href="#"><img src="/../Images/Cute.jpg" alt="" /></a> <a href="#"><img src="/../Images/Cute-Little.jpg" alt="" /></a> <a href="#"><img src="/../Images/Smooches.jpg" alt="" /></a> </div>
                <!-- end ads -->
                <div class="wrapper">
                    <!-- begin popular posts -->
                    
                    <div id="PopularPosts">
                        <h2>Thông Tin HOT</h2>
                        <ul>
                            <li>
                                <a>Bạn đang đọc báo trên trang <b>@ViewBag.UrlFeed</b> Mục:<b>@ViewBag.UrlChildFeed</b>
                                .Nếu bạn quan tâm đến tin tức trong mục này.Bạn hãy click vào<a href="http://thenews.apphb.com/Customers/RegisterFavorite?LinkFavorite=@ViewBag.LinkFavorite"><b> ĐÂY </b></a>.Chúng tôi sẽ
                                sẽ gửi tới mail của bạn khi hệ thống cập nhật tin mới :) </a>
                            </li>
                        </ul>
                    </div>
                 </div>
                    <!-- begin search -->
                    <form class="search" action="#">
                        <input type="text" name="s" id="Search" style="height:20px;" />
                        <button type="submit">Search</button>
                    </form>
                    <!-- end search -->
                    <div class="wrapper">
                        <!-- begin popular posts -->                                              
                        <div id="PopularPosts">
                            <h2>Danh Mục Tin Tức</h2>
                            <ul data-bind="foreach:  Feeds">
                                <li><a data-bind="attr: { href: '/Customers/Index?FeedID='+FeedID}, text : UrlChildFeed "></a></li>
                            </ul>
                        </div>
                        <!-- end popular posts -->
                        <!-- begin flickr photos -->
                        @Html.Action("Index", "Flick")
                        @*                    @Html.Partial("_flickrphotospartial")*@
                        <!-- end flickr photos -->
                        <!-- begin featured video -->
                        @Html.Action("Index", "Video")
                        @*                    @Html.Partial("_FeaturedVideoPartial")*@

                    </div>
                </div>
                            <!-- END sidebar -->
                            <!-- BEGIN footer -->
                            <div id="footer">
                                <p>Copyright &copy; 2014 - <a>The Web News</a> &middot; All Rights Reserved</p>
                                <p>Template by: <a>Phạm Tuyên Designer</a> | Get More <a>Đại Học Khoa Học Tự Nhiên</a></p>
            </div>
            <!-- END footer -->
        </div>
        <!-- END wrapper -->
             @*<div align=center>This template  downloaded form <a href='#'>free website templates</a></div>*@
    </body>
</html>
<script src="~/Scripts/knockout-2.1.0.js"></script>
<script type="text/javascript">
    var EmpViewModel = function () {
        //Make the self as 'this' reference
        var self = this;
        //Declare observable which will be bind with UI
        self.FeedID = ko.observable("");
        self.UrlFeed = ko.observable("");
        self.UrlChildFeed = ko.observable("");
        self.UrlSubFeed = ko.observable("");        
        self.xpathUrlPagingFeed = ko.observable("");
        self.XpathUrlFeed = ko.observable("");
        self.XpathTilte = ko.observable("");
        self.XpathPublishedDate = ko.observable("");
        self.XpathSummary = ko.observable("");
        self.XpathImageUrl = ko.observable("");
        self.XpathUrlSub = ko.observable("");
        self.Flag = ko.observable("");

        //The Object which stored data entered in the observables
        var EmpData = {
            FeedID: self.FeedID,
            UrlFeed: self.UrlFeed,
            UrlChildFeed: self.UrlChildFeed,
            UrlSubFeed: self.UrlSubFeed,            
            xpathUrlPagingFeed: self.xpathUrlPagingFeed,
            XpathUrlFeed: self.XpathUrlFeed,
            XpathTilte: self.XpathTilte,
            XpathPublishedDate: self.XpathPublishedDate,
            XpathSummary: self.XpathSummary,
            XpathImageUrl: self.XpathImageUrl,
            XpathUrlSub: self.XpathUrlSub,
            Flag: self.Flag
        };

        //Declare an ObservableArray for Storing the JSON Response
        self.Feeds = ko.observableArray([]);
        GetFeeds(); //Call the Function which gets all records using ajax call      
        function GetFeeds() {
            //Ajax Call Get All Employee Records
            $.ajax({
                type: "GET",
                url: "http://cktapp.apphb.com/api/Feeds?UrlFeed=@ViewBag.UrlFeed",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    self.Feeds(data); //Put the response in ObservableArray
                },
                error: function (error) {
                   // alert(error.status + "<--and--> " + error.statusText);
                }
            });
            //Ends Here
        }
    };
    ko.applyBindings(new EmpViewModel());
</script>

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_Layout.cshtml.REMOTE.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>The Web News</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="~/Content/style.css" />
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/jqueryui")
            @Scripts.Render("~/bundles/jqueryval")
            @Styles.Render("~/Content/themes/base/css")
            @RenderSection("scripts",required:false)
        <link type="text/css" href="~/Content/lightbox2/css/lightbox.css" rel="stylesheet" />
        <script type="text/javascript" src="~/Content/lightbox2/js/lightbox-2.6.min.js"></script>
        <script src="~/Content/js/bootstrap.min.js"></script>
        <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
        <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    </head>
    <body>
        <!-- BEGIN wrapper -->
        <div id="wrapper">
            <!-- BEGIN header -->
            @Html.Partial("_HeaderPartial")







            <!-- END header -->
            <!-- BEGIN content -->
            <div id="content">
                <!-- begin post -->
                @RenderBody()
                <!-- end post navigation -->
            </div>
            <!-- END content -->
            <!-- BEGIN sidebar -->
            <div id="sidebar">
                <!-- begin ads -->
                <div class="ads"> <a href="#"><img src="/../Images/babycute.jpg" alt="" /></a> <a href="#"><img src="/../Images/Cute.jpg" alt="" /></a> <a href="#"><img src="/../Images/Cute-Little.jpg" alt="" /></a> <a href="#"><img src="/../Images/Smooches.jpg" alt="" /></a> </div>
                <!-- end ads -->
                <div class="wrapper">
                    <!-- begin popular posts -->
                    
                    <div id="PopularPosts">
                        <h2>Thông Tin HOT</h2>
                        <ul>
                            <li>
                                <a>Bạn đang đọc báo trên trang <b>@ViewBag.UrlFeed</b> Mục:<b>@ViewBag.UrlChildFeed</b>
                                .Nếu bạn quan tâm đến tin tức trong mục này.Bạn hãy click vào<a href="http://localhost:4476/Customers/RegisterFavorite?LinkFavorite=@ViewBag.LinkFavorite"><b> ĐÂY </b></a>.Chúng tôi sẽ
                                sẽ gửi tới mail của bạn khi hệ thống cập nhật tin mới :) </a>
                            </li>
                        </ul>
                    </div>
                 </div>
                    <!-- begin search -->
                    <form class="search" action="#">
                        <input type="text" name="s" id="Search" style="height:20px;" />
                        <button type="submit">Search</button>
                    </form>
                    <!-- end search -->
                    <div class="wrapper">
                        <!-- begin popular posts -->                                              
                        <div id="PopularPosts">
                            <h2>Danh Mục Tin Tức</h2>
                            <ul data-bind="foreach:  Feeds">
                                <li><a data-bind="attr: { href: '/Customers/Index?FeedID='+FeedID}, text : UrlChildFeed "></a></li>
                            </ul>
                        </div>
                        <!-- end popular posts -->
                        <!-- begin flickr photos -->
                        @Html.Action("Index", "Flick")
                        @*                    @Html.Partial("_flickrphotospartial")*@
                        <!-- end flickr photos -->
                        <!-- begin featured video -->
                        @Html.Action("Index", "Video")
                        @*                    @Html.Partial("_FeaturedVideoPartial")*@

                    </div>
                </div>
                            <!-- END sidebar -->
                            <!-- BEGIN footer -->
                            <div id="footer">
                                <p>Copyright &copy; 2014 - <a>The Web News</a> &middot; All Rights Reserved</p>
                                <p>Template by: <a>Phạm Tuyên Designer</a> | Get More <a>Đại Học Khoa Học Tự Nhiên</a></p>
            </div>
            <!-- END footer -->
        </div>
        <!-- END wrapper -->
             @*<div align=center>This template  downloaded form <a href='#'>free website templates</a></div>*@
    </body>
</html>
<script src="~/Scripts/knockout-2.1.0.js"></script>
<script type="text/javascript">
    var EmpViewModel = function () {
        //Make the self as 'this' reference
        var self = this;
        //Declare observable which will be bind with UI
        self.FeedID = ko.observable("");
        self.UrlFeed = ko.observable("");
        self.UrlChildFeed = ko.observable("");
        self.UrlSubFeed = ko.observable("");        
        self.xpathUrlPagingFeed = ko.observable("");
        self.XpathUrlFeed = ko.observable("");
        self.XpathTilte = ko.observable("");
        self.XpathPublishedDate = ko.observable("");
        self.XpathSummary = ko.observable("");
        self.XpathImageUrl = ko.observable("");
        self.XpathUrlSub = ko.observable("");
        self.Flag = ko.observable("");

        //The Object which stored data entered in the observables
        var EmpData = {
            FeedID: self.FeedID,
            UrlFeed: self.UrlFeed,
            UrlChildFeed: self.UrlChildFeed,
            UrlSubFeed: self.UrlSubFeed,            
            xpathUrlPagingFeed: self.xpathUrlPagingFeed,
            XpathUrlFeed: self.XpathUrlFeed,
            XpathTilte: self.XpathTilte,
            XpathPublishedDate: self.XpathPublishedDate,
            XpathSummary: self.XpathSummary,
            XpathImageUrl: self.XpathImageUrl,
            XpathUrlSub: self.XpathUrlSub,
            Flag: self.Flag
        };

        //Declare an ObservableArray for Storing the JSON Response
        self.Feeds = ko.observableArray([]);
        GetFeeds(); //Call the Function which gets all records using ajax call      
        function GetFeeds() {
            //Ajax Call Get All Employee Records
            $.ajax({
                type: "GET",
                url: "http://cktapp.apphb.com/api/Feeds?UrlFeed=@ViewBag.UrlFeed",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    self.Feeds(data); //Put the response in ObservableArray
                },
                error: function (error) {
                   // alert(error.status + "<--and--> " + error.statusText);
                }
            });
            //Ends Here
        }
    };
    ko.applyBindings(new EmpViewModel());
</script>

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_ViewSwitcher.cshtml
@if (Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Chế độ Mobile 
            @Html.ActionLink("Chế độ Desktop", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Chế độ Desktop 
            @Html.ActionLink("Chế độ Mobile", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}

MVC_Auth_Facebook/MVC_Auth_Facebook/Views/Shared/_flickrphotospartial.cshtml
<h2>Những Hình Ảnh HOT Trong Ngày Trên Flickr</h2>
<div class="flickr" id="picturelist">

</div>

<script>
    $(function() {
        var url = 'http://api.flickr.com/services/rest/?method=flickr.interestingness.getList&api_key=4ee6d4ec5b8d54cdbe7a49759b63dc8b&format=json&nojsoncallback=1&per_page=9&page=1';
        $.ajax({
            url: url,
            type: 'GET',
            success: function (data) {
                $.each(data.photos.photo, function (i, item) {
                    src = "http://farm" + item.farm + ".static.flickr.com/" + item.server + "/" + item.id + "_" + item.secret + ".jpg";
                    $("#picturelist").prepend('<a data-lightbox="img"  href="'+ src +'">  <img src="' + src + ' " style="height: 80px;width: 80px" /> </a>');
                });
            }
        });
    });
</script>